### ISSUE TITLE
About the output of vbliinds_demo.py

### ISSUE THREAD

**Issue by yanglixiaoshen** [pavancm/vbliinds#2]
Thanks a lot for your excellent work!

A small question is that why the output of vbliinds_demo.py is a feature matix but not a quality score? How can I get the final quality score for one input video?

Thanks for you!

**Comment by pavancm** [comment]
Video BLIINDs algorithm is a feature extraction algorithm and this repo is it's implementation. These features can be used for obtaining quality score by learning a regression model. The learning can be done using any Video Quality Assessment (VQA) datasets which contain human opinion scores for each video.
